/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.DoctorPlaza;

import com.example.DoctorPlaza.Backend.SpringBootLauncher;
import com.example.DoctorPlaza.Frontend.SceneManager;
import com.example.DoctorPlaza.Frontend.SignInController;
import java.io.IOException;
import javafx.application.Application;
import javafx.stage.Stage;
import org.springframework.boot.SpringApplication;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }
    
    @Override
    public void init() {
        Thread backendThread = new Thread(() -> {
            SpringApplication.run(SpringBootLauncher.class); // Your backend class
        });
        backendThread.setDaemon(true); // Don't block app shutdown
        backendThread.start();
    }
    
    @Override
    public void start(Stage stage) throws IOException{
        SceneManager.setStage(stage);
        SceneManager.switchScene("com/example/DoctorPlaza/Frontend/SignIn.fxml", new SignInController());
    }

    public static void main(String[] args) {
       launch();
    }
}
