/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.DoctorPlaza;

import com.example.DoctorPlaza.Backend.SpringBootLauncher;
import com.example.DoctorPlaza.Frontend.SceneManager;
import com.example.DoctorPlaza.Frontend.controllers.SignInController;
import com.example.DoctorPlaza.Frontend.controllers.SignUpController;
import java.io.IOException;
import javafx.application.Application;
import javafx.stage.Stage;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;

public class App extends Application {
    
    private ConfigurableApplicationContext springContext;

    public String getGreeting() {
        return "Hello World!";
    }
    
    @Override
    public void init() {
        Thread backendThread = new Thread(() -> {
            springContext = SpringApplication.run(SpringBootLauncher.class); 
        });
        backendThread.setDaemon(true);
        backendThread.start();
    }
    
    @Override
    public void start(Stage stage) throws IOException{
        SceneManager.setStage(stage);
        SceneManager.switchScene("com/example/DoctorPlaza/Frontend/auth/SignIn.fxml", new SignInController());
    }
    
    @Override
    public void stop() {
        if (springContext != null) {
            System.out.println("Shutting down Spring Boot context...");
            springContext.close();
        } else {
            System.out.println("No Spring context found to shut down.");
        }
    }

    public static void main(String[] args) {
       launch(args);
    }
}
